/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.se4de;

import de.buw.se4de.gameflow.Game;

import javax.swing.*;

public class Window {
	JFrame frame;
	public Window(int width, int height, String title, Game game) {
		frame = new JFrame(title);
		frame.setSize(width,height);
		frame.setResizable(false);
		frame.add(game);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setLocationRelativeTo(null);
		frame.setVisible(true);
	}//TODO change gradle working directory

}
