/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.se4de;

import javax.swing.*;

public class Window {
	public Window(int width, int height, String title, Game game) {
		JFrame frame = new JFrame(title);
		frame.setSize(width,height);
		frame.setResizable(false);
		frame.add(game);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setLocationRelativeTo(null);
		frame.setVisible(true);
	}

	public void showrestart(){

	}

}
